# Generated by Django 6.0 on 2025-12-20 18:56

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns this cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="DiscountOffer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for the discount offer",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, help_text="Campaign start date"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, help_text="Campaign end date"),
                ),
                (
                    "available_on",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated days: Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discount Offer",
                "verbose_name_plural": "Discount Offers",
                "db_table": "discount_offers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="discount_offer_name_idx"),
                    models.Index(
                        fields=["start_date"], name="discount_offer_start_idx"
                    ),
                    models.Index(fields=["end_date"], name="discount_offer_end_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_percentage__gte", 0),
                            ("discount_percentage__lte", 100),
                        ),
                        name="valid_discount_offer_percentage",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lte", models.F("end_date"))),
                        name="valid_discount_date_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique coupon code",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only alphanumeric characters, hyphens, and underscores.",
                                regex="^[A-Za-z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        db_index=True, help_text="Date when coupon expires"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current status of the coupon",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Assign coupon to specific contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discount_offer",
                    models.ForeignKey(
                        help_text="Linked discount offer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupons",
                        to="products.discountoffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for the payment term",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "early_payment_discount",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this term offers early payment discounts",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "discount_days",
                    models.IntegerField(
                        default=0,
                        help_text="Number of days to qualify for early payment discount",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "early_pay_discount_computation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("percentage_of_total", "Percentage of Total Amount"),
                            ("fixed_amount", "Fixed Amount Discount"),
                        ],
                        help_text="Method to calculate early payment discount",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "example_preview",
                    models.TextField(
                        blank=True,
                        help_text="Example showing how this payment term works",
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default payment term",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Term",
                "verbose_name_plural": "Payment Terms",
                "db_table": "payment_terms",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="payment_term_name_idx"),
                    models.Index(
                        fields=["is_default"], name="payment_term_default_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_percentage__gte", 0),
                            ("discount_percentage__lte", 100),
                        ),
                        name="valid_discount_percentage",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("discount_days__gte", 0)),
                        name="valid_discount_days",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                ("product_category", models.CharField(max_length=100)),
                ("product_type", models.CharField(max_length=50)),
                ("material", models.CharField(blank=True, max_length=100, null=True)),
                ("sales_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sales_tax_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "purchase_tax_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("current_stock", models.IntegerField(default=0)),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("current_stock__gte", 0)),
                        name="check_current_stock_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity of the product",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="Cart this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product in the cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "db_table": "cart_items",
            },
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when purchase order was created",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the purchase order",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all line item totals",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total tax amount",
                        max_digits=12,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final total including tax",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor contact for this purchase order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="accounts.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "db_table": "purchase_orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity ordered (must be positive)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price at time of order (from Product.purchase_price)",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax percentage for this line",
                        max_digits=5,
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Line subtotal (quantity * unit_price)",
                        max_digits=12,
                    ),
                ),
                (
                    "line_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax amount for this line",
                        max_digits=12,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Line total (subtotal + tax)",
                        max_digits=12,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being ordered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="products.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        help_text="Parent purchase order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="products.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Line",
                "verbose_name_plural": "Purchase Order Lines",
                "db_table": "purchase_order_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when order was created",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the order",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all line item totals",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount amount from applied coupon",
                        max_digits=12,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final total after discount",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_coupon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coupon applied to this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="products.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who placed the order (must be portal user)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        help_text="Payment terms for this order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="products.paymentterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Order",
                "verbose_name_plural": "Sale Orders",
                "db_table": "sale_orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerInvoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "invoice_date",
                    models.DateField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date when invoice was created",
                    ),
                ),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total invoice amount (copied from order)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the invoice",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Source sale order for this invoice",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="products.saleorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Invoice",
                "verbose_name_plural": "Customer Invoices",
                "db_table": "customer_invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="SaleOrderLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity ordered (must be positive)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price at time of order (from Product.sales_price)",
                        max_digits=10,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Line total (quantity * unit_price)",
                        max_digits=12,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Parent sale order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="products.saleorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being ordered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Order Line",
                "verbose_name_plural": "Sale Order Lines",
                "db_table": "sale_order_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1,
                        help_text="Always 1 for singleton pattern",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "automatic_invoicing",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic invoice generation from confirmed orders",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="system_settings_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorBill",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "bill_date",
                    models.DateField(
                        db_index=True,
                        default=datetime.date.today,
                        help_text="Date when bill was created",
                    ),
                ),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total bill amount (copied from purchase order)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the bill",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        help_text="Source purchase order for this bill",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="products.purchaseorder",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor for this bill",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="accounts.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Bill",
                "verbose_name_plural": "Vendor Bills",
                "db_table": "vendor_bills",
                "ordering": ["-bill_date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount (must be positive)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        db_index=True, help_text="Date and time when payment was made"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                        ],
                        default="razorpay",
                        help_text="Payment method used",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay order ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Razorpay payment ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay signature for verification",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer invoice this payment is for",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="products.customerinvoice",
                    ),
                ),
                (
                    "vendor_bill",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendor bill this payment is for",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="products.vendorbill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="coupon_code_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["status"], name="coupon_status_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["expiration_date"], name="coupon_expiration_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["contact"], name="coupon_contact_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["discount_offer"], name="coupon_offer_idx"),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "used", "expired", "cancelled"])
                ),
                name="valid_coupon_status",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="cart_item_cart_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="cart_item_product_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AddIndex(
            model_name="productcolor",
            index=models.Index(
                fields=["product", "color"], name="products_pr_product_16d47d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcolor",
            unique_together={("product", "color")},
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["vendor"], name="purchase_order_vendor_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["order_date"], name="purchase_order_date_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["status"], name="purchase_order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(
                fields=["purchase_order"], name="purchase_line_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(fields=["product"], name="purchase_line_product_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="valid_purchase_line_quantity",
            ),
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(fields=["customer"], name="sale_order_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(fields=["order_date"], name="sale_order_date_idx"),
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(fields=["status"], name="sale_order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(fields=["invoice_date"], name="invoice_date_idx"),
        ),
        migrations.AddIndex(
            model_name="customerinvoice",
            index=models.Index(fields=["status"], name="invoice_status_idx"),
        ),
        migrations.AddIndex(
            model_name="saleorderline",
            index=models.Index(fields=["order"], name="sale_line_order_idx"),
        ),
        migrations.AddIndex(
            model_name="saleorderline",
            index=models.Index(fields=["product"], name="sale_line_product_idx"),
        ),
        migrations.AddConstraint(
            model_name="saleorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="valid_line_quantity"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["vendor"], name="vendor_bill_vendor_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["bill_date"], name="vendor_bill_date_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["status"], name="vendor_bill_status_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_date"], name="payment_date_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["razorpay_payment_id"], name="razorpay_payment_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer_invoice__isnull", False),
                        ("vendor_bill__isnull", True),
                    ),
                    models.Q(
                        ("customer_invoice__isnull", True),
                        ("vendor_bill__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="payment_exactly_one_fk",
            ),
        ),
    ]
