# Generated by Django 4.2.27 on 2025-12-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('product_category', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=50)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_stock', models.IntegerField(default=0)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('current_stock__gte', 0)), name='check_current_stock_non_negative'),
        ),
        migrations.AddIndex(
            model_name='productcolor',
            index=models.Index(fields=['product', 'color'], name='products_pr_product_16d47d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'color')},
        ),
    ]
