# Generated by Django 4.2.27 on 2025-12-20 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_paymentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOffer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name for the discount offer', max_length=255, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('start_date', models.DateField(db_index=True, help_text='Campaign start date')),
                ('end_date', models.DateField(db_index=True, help_text='Campaign end date')),
                ('available_on', models.CharField(blank=True, help_text='Comma-separated days: Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Offer',
                'verbose_name_plural': 'Discount Offers',
                'db_table': 'discount_offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='discount_offer_name_idx'), models.Index(fields=['start_date'], name='discount_offer_start_idx'), models.Index(fields=['end_date'], name='discount_offer_end_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='discountoffer',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='valid_discount_offer_percentage'),
        ),
        migrations.AddConstraint(
            model_name='discountoffer',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='valid_discount_date_range'),
        ),
    ]
