# Generated by Django 4.2.27 on 2025-12-20 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_discountoffer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must contain only alphanumeric characters, hyphens, and underscores.', regex='^[A-Za-z0-9_-]+$')])),
                ('expiration_date', models.DateField(db_index=True, help_text='Date when coupon expires')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Current status of the coupon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Optional: Assign coupon to specific contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('discount_offer', models.ForeignKey(help_text='Linked discount offer', on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='products.discountoffer')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='coupon_code_idx'), models.Index(fields=['status'], name='coupon_status_idx'), models.Index(fields=['expiration_date'], name='coupon_expiration_idx'), models.Index(fields=['contact'], name='coupon_contact_idx'), models.Index(fields=['discount_offer'], name='coupon_offer_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'used', 'expired', 'cancelled'])), name='valid_coupon_status'),
        ),
    ]
