# Generated by Django 4.2.27 on 2025-12-20 09:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_coupon_coupon_valid_coupon_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when order was created')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current status of the order', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line item totals', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount from applied coupon', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total after discount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_coupon', models.ForeignKey(blank=True, help_text='Coupon applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.coupon')),
                ('customer', models.ForeignKey(help_text='Customer who placed the order (must be portal user)', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale Order',
                'verbose_name_plural': 'Sale Orders',
                'db_table': 'sale_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Quantity ordered (must be positive)', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of order (from Product.sales_price)', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Line total (quantity * unit_price)', max_digits=12)),
                ('order', models.ForeignKey(help_text='Parent sale order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.saleorder')),
                ('product', models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='products.product')),
            ],
            options={
                'verbose_name': 'Sale Order Line',
                'verbose_name_plural': 'Sale Order Lines',
                'db_table': 'sale_order_lines',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order'], name='sale_line_order_idx'), models.Index(fields=['product'], name='sale_line_product_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='saleorderline',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='valid_line_quantity'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['customer'], name='sale_order_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['order_date'], name='sale_order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['status'], name='sale_order_status_idx'),
        ),
    ]
