# Generated by Django 4.2.27 on 2025-12-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_saleorder_saleorderline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(auto_now_add=True, db_index=True, help_text='Date when invoice was created')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount (copied from order)', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current status of the invoice', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Source sale order for this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='products.saleorder')),
            ],
            options={
                'verbose_name': 'Customer Invoice',
                'verbose_name_plural': 'Customer Invoices',
                'db_table': 'customer_invoices',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['invoice_date'], name='invoice_date_idx'), models.Index(fields=['status'], name='invoice_status_idx')],
            },
        ),
    ]
