# Generated by Django 4.2.27 on 2025-12-20 11:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customer_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total bill amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendor Bill',
                'verbose_name_plural': 'Vendor Bills',
                'db_table': 'vendor_bills',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateTimeField(db_index=True, help_text='Date and time when payment was made')),
                ('method', models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='razorpay', help_text='Payment method used', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay order ID', max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, help_text='Razorpay payment ID', max_length=255, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_invoice', models.ForeignKey(blank=True, help_text='Customer invoice this payment is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='products.customerinvoice')),
                ('vendor_bill', models.ForeignKey(blank=True, help_text='Vendor bill this payment is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='products.vendorbill')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date'], name='payment_date_idx'), models.Index(fields=['razorpay_payment_id'], name='razorpay_payment_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('customer_invoice__isnull', False), ('vendor_bill__isnull', True)), models.Q(('customer_invoice__isnull', True), ('vendor_bill__isnull', False)), _connector='OR'), name='payment_exactly_one_fk'),
        ),
    ]
