# Generated by Django 4.2.27 on 2025-12-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_cart_saleorder_payment_term_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleorder",
            name="payment_term",
            field=models.ForeignKey(
                help_text="Payment terms for this order",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="products.paymentterm",
            ),
        ),
    ]
