# Generated by Django 6.0 on 2025-12-20 17:59

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_vendor_role'),
        ('products', '0011_add_purchase_orders_and_enhance_vendor_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorbill',
            options={'ordering': ['-bill_date'], 'verbose_name': 'Vendor Bill', 'verbose_name_plural': 'Vendor Bills'},
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='due_date',
            field=models.DateField(default=products.models.get_default_due_date, help_text='Payment due date'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='purchase_order',
            field=models.ForeignKey(help_text='Source purchase order for this bill', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='products.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total bill amount (copied from purchase order)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor for this bill', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='accounts.contact'),
        ),
    ]
